---
title: "Food"
author: "Sharmarke, Evan & Mars"
date: "2023-2-24"
output: html_document
runtime: shiny
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
pacman::p_load(tidyverse,readxl,shiny,dplyr,gapminder)

debugMode <- TRUE
showcodeMode <- FALSE

```

```{r fields processing, include=showcodeMode, message = debugMode, warning = debugMode}
CPIHistoricalData <- read_excel("historicalcpi.xlsx", skip = 1)
CPIHistoricalDataRaw <- CPIHistoricalData %>%
  remove_missing() %>%
  mutate(`Consumer Price Index item` = as.factor(`Consumer Price Index item`)) %>%
  mutate_if(is.character, as.numeric) %>% 
  rename(cpiItem = `Consumer Price Index item`)
#head(CPIHistoricalDataRaw)
CPIHistoricalDataRaw$cpiItem
CPIHistoricalDataRaw <- CPIHistoricalDataRaw %>% 
  mutate(level = case_when((cpiItem %in% c('All food'))~ 1,
                           (cpiItem %in% c('Food away from home','Food at home')) ~ 2,
                           (cpiItem %in% c('Meats, poultry, and fish', 'Eggs', 'Dairy products', 'Fats and oils', 'Fruits and vegetables', 'Sugar and sweets','Cereals and bakery products', 'Nonalcoholic beverages', 'Other foods')) ~ 3,
                           (cpiItem %in% c('Meats', 'Poultry', 'Fish and seafood', 'Fresh fruits and vegetables', 'Processed fruits and vegetables')) ~ 4,
                           (cpiItem %in% c('Beef and veal', 'Pork', 'Other meats', 'Fresh fruits', 'Fresh vegetables')) ~ 5,
                           TRUE ~ 0
                           ),
         level = as.factor(level)
         )
CPIHistoricalDataRaw %>% 
  select(cpiItem, level) %>%
  view()
#head(CPIHistoricalDataRaw)
CPIHistoricalLong <- CPIHistoricalDataRaw %>% 
  pivot_longer(cols = !c(cpiItem, level)) %>%
  rename(year = name, percentchange = value) %>% 
  mutate(percentchange = round(percentchange*0.01, 3))
#head(CPIHistoricalDataRaw)
CPIHistoricalDataFrame <- read_excel("historicalcpi.xlsx", sheet = "df")
head(CPIHistoricalDataFrame)
```


## Introduction

## CPI Data {.tabset}

### Historical CPI

```{r historical, echo=showcodeMode, message = debugMode, warning = debugMode}

inputPanel(
  selectInput("cpiHistoricalItem", 
              label = "Item of showing in Graph",
              choices = unique(CPIHistoricalDataFrame$item),
              selected = "All food",
              multiple = TRUE),
  sliderInput("cpiHistoricalYear", label = "Year Range",
              min = 1974, max = 2021, value = c(1974,2021), step = 1),
)

renderPlot({
  ggplot(data = CPIHistoricalDataFrame,
       mapping = aes(x = year,
                     y = percentChange,
                     color = item)) + 
  geom_col() + guides(fill = FALSE) + 
  theme(legend.position = "left") + 
  labs(
    x = NULL,
    y = "Changes in Year",
    title = "Historical CPI"
  )
})
renderDataTable(
  CPIHistoricalDataFrame$item %>%
  filter(item %in% input$cpiHistoricalItem)
)
head(CPIHistoricalDataRaw)

```

### Forecast CPI

```{r forecast, echo=showcodeMode, message = debugMode, warning = debugMode}

```
